name: we_flutter
description: a new mvvm flutter project base on riverpodã€dio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  logger: ^1.3.0
  dio: ^5.0.3
  dio_cookie_manager: ^2.1.2
  path_provider: ^2.0.13
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^3.0.1
  dio_smart_retry: ^5.0.0
  flutter_smart_dialog: ^4.9.0+3
  flutter_swiper_view: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts: #google fonts:  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    - family: zhimangxing
      fonts:
        - asset: assets/fonts/ZhiMangXing-Regular.ttf
